# Generated by Django 4.1.3 on 2022-12-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_time_spent_on_site', models.FloatField()),
                ('age', models.IntegerField()),
                ('area_income', models.FloatField()),
                ('daily_internet_usage', models.FloatField()),
                ('ad_topic_line', models.TextField()),
                ('city', models.TextField()),
                ('male', models.BooleanField()),
                ('country', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('clicked_on_ad', models.BooleanField()),
            ],
        ),
    ]
